Feature/guides preview
jordanopensource/start-web pull request #15
Opened 2021-08-08 12:44 UTC by Ashaqra

### Guides Preview 

- Add guides preview component .
- Add store modules and store index .
- create a function in store for fetching API and getting data from it .

2021-08-09 10:10 UTC, wissamataleh requested changes
- Please refer to the latest docs for creating Nuxt Vuex store modules. https://nuxtjs.org/docs/2.x/directory-structure/store

2021-08-18 13:47 UTC, geokhoury commented
#### 📝Changed routes:


| [**/knowledgebase**](https://start-b2n2pm3hg-josa.vercel.app/knowledgebase) |
|:-:|
|<a href="https://start-b2n2pm3hg-josa.vercel.app/knowledgebase"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/KHo-L-Cms13TkxoACwKE40MfrsFjKuhELKZ2hPZejx9Gd-eex3AipPIYQE7XMMZS1L1MnQNwW42C2xdy8qkNTA.png&w=600" alt="Screenshot of /knowledgebase" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/zOrw2NHa9hv9qx159PT7go6E74yWr4maUIAGgo8F24bgD8l5c5Q2Sfexmv_8gU5FkOU3ZdU8SzU6xRFSzAeXew.png">(view full size)</a> |







Commit 0e2e15aa1c3e8342f9cf0b38e211df8bc1c1468a (https://start-b2n2pm3hg-josa.vercel.app).

2021-08-19 09:41 UTC, wissamataleh submitted a review, later dismissed

2021-08-21 18:31 UTC, geokhoury commented
#### 📝 Changed routes:


| [**/knowledgebase**](https://start-e4lkbrfcm-josa.vercel.app/knowledgebase) |
|:-:|
|<a href="https://start-e4lkbrfcm-josa.vercel.app/knowledgebase"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/pZkrVLKWDCdbtxR6pulbsGB4LgOZFM_v5Kmdbe9CvWIzbrVcuhmPvcuWv_sba0rYYdKgCRk-AT4SfrqJW-tzbA.png&w=600" alt="Screenshot of /knowledgebase" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/hMzNl1kYJftvprfbEgiXiwbXo8fhf3LTOhYZ1uYUuGMs4uebpHlbtVqdaE8Q0se1l16ObAvVz7UbW_CtOkHXEg.png">(view full size)</a> |







Commit 53804631236676c9bbdc79dbce1be15d131e651c (https://start-e4lkbrfcm-josa.vercel.app).

2021-08-21 18:54 UTC, wissamataleh approved these changes

2021-08-21 18:55 UTC, merged