File and directory clean up
jordanopensource/start-web pull request #19
Opened 2021-08-11 10:02 UTC by fmubaidien

Will do weekly clean ups in order to make sure the code base is constantly applying standards and staying organized correctly

2021-08-12 08:36 UTC, wissamataleh requested changes
- Also move dashboard pages into `/dashboards` directory.

2021-08-16 12:21 UTC, geokhoury commented
#### 📝Changed routes:


| [**/dashboards/FAQ**](https://start-igzcrz4s9-josa.vercel.app/dashboards/FAQ) | [**/dashboards/knowledgebase**](https://start-igzcrz4s9-josa.vercel.app/dashboards/knowledgebase) |
|:-:|:-:|
|<a href="https://start-igzcrz4s9-josa.vercel.app/dashboards/FAQ"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/wvzjx8KGLfiHArhPieMwJDc_xfI1QEonBZLFVknNIzVCiRxRuXWpN10EddmKbfuVkOlWfo71_EmdVhN2osUDUg.png&w=600" alt="Screenshot of /dashboards/FAQ" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/JpBBpOty5QtG7o22-4YRnnoGrijQKdj13CULXAcnnGHIqkXpZZKl-5kkKWDB3f3J5XaeUQWNcKA9HrjT8X4NJQ.png">(view full size)</a> |<a href="https://start-igzcrz4s9-josa.vercel.app/dashboards/knowledgebase"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/DyZ52sFoCnKRVhU4Jp2yWi3KHVrtxTQLZKZr-KZzbJmYInp2QlLXSrwF3SkJ1txQC0lJ03FuGO2VWLC9LHjBkw.png&w=600" alt="Screenshot of /dashboards/knowledgebase" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/zUvtxqXYO1cIQ0YRx8vS4jxBNMig9ebRwEEh1fLZJIXA2SJT-KM_QbMftYXIXOygi235i4JaPXESRdpv8BVeVw.png">(view full size)</a> |



| [**/dashboards/quicklinks**](https://start-igzcrz4s9-josa.vercel.app/dashboards/quicklinks) | [**/dashboards/services**](https://start-igzcrz4s9-josa.vercel.app/dashboards/services) |
|:-:|:-:|
|<a href="https://start-igzcrz4s9-josa.vercel.app/dashboards/quicklinks"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/2aZLosWkfVv9kVqYlGg2LEo9oB213gPza3NF2G7sbJWoaHHon_2Yj1_dteBvlQTBz00Zn4R89fLZN8G5m7Qqdw.png&w=600" alt="Screenshot of /dashboards/quicklinks" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/CKTwnqCZMGCV7JmbjVvjojmdGJULsAVhy2JB_hfhdzHBfe4dfq9ylgoinbc814AX4bTy-_fZhC0IxMR_xzDeOA.png">(view full size)</a> |<a href="https://start-igzcrz4s9-josa.vercel.app/dashboards/services"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/X2t0YkSlyd3zWthv6spg3SRdGDPH6PoWhun1ZnJW0Du2HDjGdUeajyIr_bcpHuCBq89MSJZXKvAKhm7WD0HqaQ.png&w=600" alt="Screenshot of /dashboards/services" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/5cP3l3dhuyc515rS67fX9DG1F54baYrxN8Qgic_TiSkzOcrpFmeaz36Os-X9Xp3svxxZuw_7Z9inF6sSQScvkQ.png">(view full size)</a> |







Commit ffb1bee21d3e66f728243e49465dfda75eaf3bfd (https://start-igzcrz4s9-josa.vercel.app).

2021-08-19 09:18 UTC, wissamataleh approved these changes

2021-08-21 19:33 UTC, wissamataleh approved these changes

2021-08-21 19:33 UTC, merged