Page menu component
jordanopensource/start-web pull request #2
Opened 2021-07-14 08:53 UTC by fmubaidien

Created a pagebutton component and a page menu component, added pages to be linked to through clicking on the menu

2021-07-14 08:58 UTC, geokhoury commented
#### 📝Changed routes:


| [**/FAQ**](https://start-mwjju5pw1-josa.vercel.app/FAQ) | [**/guides**](https://start-mwjju5pw1-josa.vercel.app/guides) |
|:-:|:-:|
|<a href="https://start-mwjju5pw1-josa.vercel.app/FAQ"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/H7Az74RsjvDCjaZ1-hkPwVRu4vsAS20SgVkI4z5YY9wV_fMwr5uhuHy2xl_n8De95G3LU4jqRHcS52nWls-MIQ.png&w=600" alt="Screenshot of /FAQ" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xCeZ5rSUDhapA3E4mRbHe0rke-SmhaDdLty-6NAVqyR302P9MtmBHklGHJJH330XGB6gFpOl6SxldLTPJrmHqg.png">(view full size)</a> |<a href="https://start-mwjju5pw1-josa.vercel.app/guides"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/b5QdGLLhpB9nk-F9gc7kdxAdFzFvkMvn0RLPwww8eTTI0aesz5X6WCemQbLogMFW6VWGuOfkm7irSQtUdu-V0Q.png&w=600" alt="Screenshot of /guides" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/b1L5w2uohh_KM8Egp7pSs4jL0_Bub1du7-F35FpLcjcHai8XhGJSfL2W8-BufYhSVUuhWK2wYSCYmd2m-g6big.png">(view full size)</a> |



| [**/knowledgebase**](https://start-mwjju5pw1-josa.vercel.app/knowledgebase) | [**/questions**](https://start-mwjju5pw1-josa.vercel.app/questions) |
|:-:|:-:|
|<a href="https://start-mwjju5pw1-josa.vercel.app/knowledgebase"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/_ZWpzIz_FOia6P_FYA6GKK4ffXL7S73XYYb-KBcPrjPOhLaL1JjCdeld-7_pLr00Xo_-jMTyxwYQwN2bhb1-dg.png&w=600" alt="Screenshot of /knowledgebase" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/NABEy3ulbhsWtCfC603BDkBLFrOKC0Jd4injbgaTYNC2hGikod5iOJhUkVrETSa0M6_dUfbNze-JWbRODhfFHA.png">(view full size)</a> |<a href="https://start-mwjju5pw1-josa.vercel.app/questions"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/HeksO41nxAfwhx7lmfBkjaiDwIuaIuPlvriveaZ16mIrHEQe6DbLTugV6m4CQj5OmvBcxhbNDQCuiaILQh2O1Q.png&w=600" alt="Screenshot of /questions" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/sqcOS5uApVFPywaoaJ1tp3jN5d33e54zlDPdaXX1nFcF3IO7V6pGdtS-EyrwkXT7vsAGpT_VIV1Tl9gZFxz0UQ.png">(view full size)</a> |



| [**/quicklinks**](https://start-mwjju5pw1-josa.vercel.app/quicklinks) | [**/services**](https://start-mwjju5pw1-josa.vercel.app/services) |
|:-:|:-:|
|<a href="https://start-mwjju5pw1-josa.vercel.app/quicklinks"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/bOBGg6tnZAXfe48bMMNY_yXt69DulUU0E_1GEkaSf8bgSv0SXnDXWB8t5BbKa01lRmvmDW-X1964_GHhRatRXA.png&w=600" alt="Screenshot of /quicklinks" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/_2AbzusA0fale49yKFayUDUT60Z0iT32vpsP7IfWlc9T72Hxk5eOoLv06zX5FKN73hEpndh8ETQyfyKMJB7ewA.png">(view full size)</a> |<a href="https://start-mwjju5pw1-josa.vercel.app/services"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/9-zEHsKsv34KyRK47438IVEdVuZQLWiDwjXgSTpAm2OwdFHd2qLM5VzOCRMSD68JnCV9dGt2zWcLi5dzIAIJAA.png&w=600" alt="Screenshot of /services" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/gf7uXSx-rdM_KNJ1L2gCFcVQdz6clJjVz_BwEkOauv9H2ThqwuPchtg4UQY3fxpL3boBXTz6fB-3PKifFAXgfA.png">(view full size)</a> |







Commit 6ec595f59c9921ae7995902d59677484e1c5fd61 (https://start-mwjju5pw1-josa.vercel.app).

2021-07-18 08:15 UTC, wissamataleh requested changes
1- Review comments on files.
2- Delete all test pages.
3- Revert deleting `package-lock.json`

2021-07-18 08:15 UTC, wissamataleh commented on components/PageMenu.vue
> +    <h3 class="heading">Pages</h3>
* Remove class definitions for styling, and add styling for headers in typography css

2021-07-18 08:15 UTC, wissamataleh commented on components/PageMenu.vue
> +  ul {
Use classes to style menu

2021-07-18 08:15 UTC, wissamataleh commented on components/PageMenu.vue
> +<style>
Use scoped style

2021-07-28 14:05 UTC, wissamataleh commented
- Use hyphens in classes instead of camel case

2021-07-29 12:23 UTC, closed without merging