Add user component
jordanopensource/start-web pull request #4
Opened 2021-07-18 06:36 UTC by Ashaqra

2021-07-18 06:36 UTC, geokhoury commented
#### 📝Changed routes:


| [**/**](https://start-2p4viln13-josa.vercel.app/) |
|:-:|
|<a href="https://start-2p4viln13-josa.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/fSfIvpfezEZJe0nqH3qUIXaXFY7JVZKHFqYXyaQFqLBPgAlJVtQSYFpE77gai47PlQq5dhztwA9M6BuQDkIptg.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/y9noUt2c7C9XOEN0kmIILWSRlAt9rmusdZ3f_vBjm4OnenMclnTb0cq5bdqy0ojWPCMGHZl3_TIZVMGbEqvXUQ.png">(view full size)</a> |







Commit 84135211e39e4dae1f75f16b7ce19088b7ca42cd (https://start-2p4viln13-josa.vercel.app).

2021-07-18 08:45 UTC, wissamataleh requested changes
1- Add PR description.
2- Review comments.

2021-07-18 08:45 UTC, wissamataleh commented on components/User.vue
> +        Abdalla Shaqra
Use `props` with a default value instead

2021-07-18 08:45 UTC, wissamataleh commented on components/User.vue
> +      <p class="text-sm text-gray-300">
Replace with **`<a>`**

2021-07-18 08:45 UTC, wissamataleh commented on components/User.vue
> +  name: 'User'
* Change component name to `UserMenu`

2021-07-18 08:45 UTC, wissamataleh commented on components/User.vue
> +  width: 37px;
* Use `rem` instead of `px`

2021-07-18 08:45 UTC, wissamataleh commented on components/User.vue
> +  font-family: 'Courier New', Courier, monospace;
* Typography styles should only be in global CSS

2021-07-18 08:45 UTC, wissamataleh commented on components/User.vue
> +<style scoped>
* Use `TailwindCSS`

2021-07-31 23:03 UTC, wissamataleh requested changes

2021-07-31 23:03 UTC, wissamataleh commented on components/UserMenu.vue
> +          userImage: '~/static/profile.png'
- Move image to static images folder

2021-08-21 19:35 UTC, merged